### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by lbsha** [debasishg/scala-redis#109]
19:03:34.068 [stats-system-akka.actor.default-dispatcher-9] ERROR akka.actor.OneForOneStrategy - Protocol error: Got (1,[B@52c7e2d4) as initial reply byte
java.lang.Exception: Protocol error: Got (1,[B@52c7e2d4) as initial reply byte
    at com.redis.Reply$$anonfun$6.applyOrElse(RedisProtocol.scala:94) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.Reply$$anonfun$6.applyOrElse(RedisProtocol.scala:92) ~[redisclient_2.10-2.13.jar:2.13]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) ~[scala-library-2.10.4.jar:na]
    at com.redis.Reply$$anonfun$5.applyOrElse(RedisProtocol.scala:74) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.Reply$$anonfun$5.applyOrElse(RedisProtocol.scala:74) ~[redisclient_2.10-2.13.jar:2.13]
    at scala.PartialFunction$OrElse.apply(PartialFunction.scala:162) ~[scala-library-2.10.4.jar:na]
    at com.redis.Reply$class.receive(RedisProtocol.scala:113) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.RedisClient.receive(RedisClient.scala:91) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.R$class.asListPairs(RedisProtocol.scala:143) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.RedisClient.asListPairs(RedisClient.scala:91) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.SortedSetOperations$$anonfun$zrangeWithScore$1.apply(SortedSetOperations.scala:41) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.SortedSetOperations$$anonfun$zrangeWithScore$1.apply(SortedSetOperations.scala:41) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.Redis$class.send(RedisClient.scala:21) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.RedisClient.send(RedisClient.scala:91) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.SortedSetOperations$class.zrangeWithScore(SortedSetOperations.scala:41) ~[redisclient_2.10-2.13.jar:2.13]
    at com.redis.RedisClient.zrangeWithScore(RedisClient.scala:91) ~[redisclient_2.10-2.13.jar:2.13]

**Comment by tlcs** [comment]
The same problem here and when I am create a new instance of client each time before call this problem is gone (as @mavarazy noticed)

**Comment by billoneil** [comment]
I recently ran into this issue and the cause was misusing a lower level api.

Original (Not sure why we didn't use the built in ping before maybe we used an older version that did not have it?)
```
rcp.withClient { client =>
  client.send[String]("PING")("PONG") match {
    case "PONG" => Result.healthy()
    case _ => Result.unhealthy("No connection to Redis")
  }
}
```

Fixed
```
rcp.withClient { client =>
  val result = client.ping
  result match {
    case Some("PONG") => Result.healthy()
    case _ => Result.unhealthy("No connection to Redis")
  }
}
```

I feel like the `send` API should be private and hidden from the API consumers. It took quite a while to figure out that the signature `def send[A](command: String)(result: => A): A =` result must consume the input stream from the response or the connection will be returned to the pool in a bad state. The correct send signature would have been `send("PING")(asString)`

Alternatively you can change the code to make sure the input stream is flushed when returning a connection to the pool. This is the approach a lot of database connection pools use. They ensure connections returned to the pool are in some base state.

**Comment by seanmcl** [comment]
+1.  I ran into this reusing a connection as well.  v3.1

**Comment by DBassel** [comment]
+1 on 3.0

**Comment by cainj** [comment]
+1 on 3.0

**Comment by yabooc** [comment]
+1 on 3.0

**Comment by charlesfaustin** [comment]
+1 on 3.3

**Comment by mohittt8** [comment]
+1 on 3.3

**Comment by ezhulkov** [comment]
+1 on 3.4
thanks to @billoneil approach with ping

**Comment by michalwarecki** [comment]
+1 on 3.4

**Comment by rmccullagh** [comment]
+ 1 on 3.4. This occurs randomly is isn't reproducible

**Comment by debasishg** [comment]
Thanks for reporting. I will take a look though I am struggling for free cycles with all the other stuff going around. Just a few questions ..

1. Is there a piece of code that can possibly give this error ? I know it may be a race condition and is not reproducible. But a piece that can possibly give this error will help in testing.
2. Has anyone found a workaround for this ? Any suggestions, any best practice that help avoid this error ?

Any other suggestions ?

**Comment by ezhulkov** [comment]
@debasishg 
You can take a look at my piece of code - with this code the error occurs often and reproducible.
I found workaround but it's not production ready. If you create new client for every request the error is gone.
Artifact is "net.debasishg" %% "redisclient" % "3.4"
Scala version is 2.12.2
Redis server is 3.2.9

**Comment by debasishg** [comment]
Thanks @ezhulkov - I will take a look.

**Comment by billoneil** [comment]
I haven't looked at this in a very long time but from what I can remember the issue is related to returning a dirty buffer back to the pool. In the provided example `println(redisClient.ping)` it calls ping but I believe the bytes are never read when the connection gets returned to the pool. The next connection then starts writing to it again and you end up in a weird state.

**Comment by ezhulkov** [comment]
Sounds reasonable. In my case this error happens even without ping. 
Might be result of the set command (ok) mixed with get command

**Comment by billoneil** [comment]
Right that was just an example I think anything that uses the `send` command can leave the connection in a dirty state if it's not consumed. Just my best guess.

**Comment by debasishg** [comment]
I tried with the following test snippet ..

```scala
package com.redis

import org.scalatest.FunSpec
import org.scalatest.BeforeAndAfterEach
import org.scalatest.BeforeAndAfterAll
import org.scalatest.Matchers
import org.scalatest.junit.JUnitRunner
import org.junit.runner.RunWith


@RunWith(classOf[JUnitRunner])
class FooSpec extends FunSpec 
                     with Matchers
                     with BeforeAndAfterEach
                     with BeforeAndAfterAll {

  val r = new RedisClient("localhost", 6379)

  override def beforeEach = {
  }

  override def afterEach = {
    r.flushdb
  }

  override def afterAll = {
    r.disconnect
  }

  describe("keys") {
    it("should fetch keys") {
      r.set("key-1", "value-1")
      r.set("key-2", "value-2")
      (1 to 10000).foreach {_ =>
        println(r.ping)
        r.get("key-2")
        r.get("key-1")
      }
    }
  }
}
```
Also tried putting the `set` within the loop. Could not replicate the error once. Am I missing something ? Can you please confirm if the error occurs if *only* redis is used and no other library like Akka is present in the mix ? I tried with Redis 3.2.9 on my Mac Air running Scala 2.12.1.

Need some more help trying to replicate the error.

**Comment by billoneil** [comment]
I believe it is related to the lazy evaluation of the `send` api. When you call toString of ping it will flush the buffer. If you just call `r.ping` and do nothing with it it can leave the connection in a weird state. I also think it might be related to multi threading so maybe try a client with a very small pool size and hit it with multiple threads trying to force a connection to a bad state.

**Comment by debasishg** [comment]
I tried with just the `r.ping` without the `println` because I also was thinking of the flush situation. Could not replicate the problem. 

For multithreading the recommended way is to use the pool - you cannot use a single `RedisClient` in a multithreaded environment. I will test the pool (as u suggested), but I thought some people are getting the exception even on single `RedisClient`s. Hence I was thinking if it could be a side-effect of some other library being used together.

**Comment by debasishg** [comment]
When using the pool, if a connection gets into a bad state (somehow, maybe the thread in which the connection was being used dies) and gets returned to the pool in the bad state, we can do a `reconnect` when we return the connection to the pool (https://github.com/debasishg/scala-redis/blob/master/src/main/scala/com/redis/Pool.scala#L47). The `reconnect` will initialize the connection. WDYAT ?

I have not yet been able to replicate the problem myself. Just some thoughts based on the discussion above. But can I assume that the issue occurs only with pool and NOT with using a single client ? And just to reiterate a single `RedisClient` cannot be used in a multithreaded mode. You need to use a pool for that.

**Comment by masonkirchner** [comment]
@debasishg Yes, I am running into this issue while using a pool. Is there any established way to fix this?

**Comment by debasishg** [comment]
I will take a look over this weekend.

**Comment by validol-ekb** [comment]
Maybe, it'll help you. If we do such trick 
```scala
object RedisClientTest extends App {

  val r = new RedisClient("localhost", 6379)

  println(s"Get 1 result ${r.get("vvl:qm")}")

  r.subscribe("vvl.qm") { m =>
    println(s"Subscribe 1 result $m")
  }

  Thread.sleep(3000)

  r.unsubscribe("vvl.qm")
  println("Unsubscribe 1 was finished")

  Thread.sleep(3000)
  r.pubSub = false

  println(s"Get 2 result ${r.get("vvl:qm")}")

  r.subscribe("vvl.*") { m =>
    println(s"Subscribe 2 result $m")
  }

  Thread.sleep(3000)

  r.unsubscribe("vvl.*")
  println("Unsubscribe 2 was finished")

  Thread.sleep(3000)
  r.pubSub = false

  println(s"Get 3 result ${r.get("vvl:qm")}")
}
```
we won't receive any exception.

**Comment by validol-ekb** [comment]
I've discovered that my problem take place only when I'm trying to send some messages (e.g. GET or SET) within connection, which is already in subscription state. It isn't correct due redis official documentation https://redis.io/commands/subscribe. I think we should add some checks in RedisClient class and avoid this error explicitly.

**Comment by debasishg** [comment]
Thanks for all these pointers .. I will take a look over the weekend.

**Comment by debasishg** [comment]
@validol-ekb  Here's a PR that fixes the issue (I think) .. Can u pls check ? https://github.com/debasishg/scala-redis/pull/207

**Comment by validol-ekb** [comment]
@debasishg I've checked fix. Works fine! Thank you.

**Comment by debasishg** [comment]
Thanks .. I will merge the PR in the master and have a release soon ..

**Comment by kubukoz** [comment]
I just hit this, any plans for a release? :)

**Comment by debasishg** [comment]
Released .. should hit maven central on next sync.

**Comment by kubukoz** [comment]
Seems to work (at least for now), thanks!

**Comment by Manc** [comment]
Hi, I'm a new user of this client and seem to have the same or similar problem. I'm on version 3.7.

When I use one client instance to subscribe, unsubscribe and subscribe again and then receive a message on a subscribed channel, I get an error (`E`) like this: `Protocol error: Got (3,[B@4b32b6db) as initial reply byte`.

**Comment by debasishg** [comment]
@Manc Can u please send a failing test case that I can check ?

**Comment by zcourts** [comment]
I've just made sure my access to the client is thread safe using:
```
  val client = new ThreadLocal[RedisClient]() {
    override def initialValue(): RedisClient = new RedisClient(host, port)
  }
```
Prior to this, any use of the client would lead to this error. Using a combination of `get`, `set`, `lpush` and `lrange`

**Comment by schulace** [comment]
The above was my problem as well. I was accessing the client from 2 separate threads, which is what caused this behavior. If you're reading this years from now, make sure that each instance of the client is only accessed by 1 thread at a time. I thought I was safe since I was using actors and those are supposed to avoid a lot of concurrency issues but I still had accesses to this from separate threads.

**Comment by pritchett** [comment]
> I've just made sure my access to the client is thread safe using:
> 
> ```
>   val client = new ThreadLocal[RedisClient]() {
>     override def initialValue(): RedisClient = new RedisClient(host, port)
>   }
> ```
> Prior to this, any use of the client would lead to this error. Using a combination of `get`, `set`, `lpush` and `lrange`

This solution has also worked for my project.

**Comment by beikern** [comment]
version `3.10` still reproduces this issue.

> I've just made sure my access to the client is thread safe using:
> 
> ```
>   val client = new ThreadLocal[RedisClient]() {
>     override def initialValue(): RedisClient = new RedisClient(host, port)
>   }
> ```
> 
> Prior to this, any use of the client would lead to this error. Using a combination of `get`, `set`, `lpush` and `lrange`

This workaround creates a new redis client per thread, right? I suppose it can lead to memory problems if there're a lot of threads using the redis client, am I wrong?
