### ISSUE TITLE
Pipelineing HyperLogLog throws a NullPointerException

### ISSUE THREAD

**Issue by xtreme-josh-wilks** [debasishg/scala-redis#140]
When pipelining a HyperLogLog command, it results in a NullPointerException:
```
    val r = new RedisClient("192.168.0.104", 6379)
    r.pipeline { p =>
      p.pfadd("kAdd", "v")
    }.get
```
```
java.lang.NullPointerException
	at com.redis.HyperLogLogOperations$class.pfadd(HyperLogLogOperations.scala:9)
	at com.redis.RedisClient$PipelineClient.pfadd(RedisClient.scala:172)
	at $anonfun$1.apply(<console>:13)
	at $anonfun$1.apply(<console>:12)
	at com.redis.RedisClient.pipeline(RedisClient.scala:108)
```

**Comment by debasishg** [comment]
Thanks for reporting this. The problem is with https://github.com/debasishg/scala-redis/blob/master/src/main/scala/com/redis/HyperLogLogOperations.scala#L9 doing the ```.get``` which gives the ```NullPointerException``` during pipelining. I will have to change the hyperloglog APIs to return ```Option``` - an API change but have to do it for correctness sake.
