### ISSUE TITLE
lpush and rpop stuck

### ISSUE THREAD

**Issue by mdespriee** [debasishg/scala-redis#194]
We found our application stuck today, with 2 threads waiting forever. One blocked doing a lpush to Redis, the other blocked doing a rpop. 
Redis server was fine. No log or anything suspicious on server side.

Java 8
redis-client 3.2

Any idea for a possible cause of this ?

**Comment by mdespriee** [comment]
The 2 stacks: 
```
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:264)
        - waiting to lock <0x000000008af22bf8> (a java.io.BufferedInputStream)
        at com.redis.IO$class.readLine(IO.scala:88)
        at com.redis.RedisClient.readLine(RedisClient.scala:94)
        at com.redis.Reply$class.receive(RedisProtocol.scala:120)
        at com.redis.RedisClient.receive(RedisClient.scala:94)
        at com.redis.R$class.asLong(RedisProtocol.scala:139)
        at com.redis.RedisClient.asLong(RedisClient.scala:94)
        at com.redis.ListOperations$$anonfun$lpush$1.apply(ListOperations.scala:10)
        at com.redis.ListOperations$$anonfun$lpush$1.apply(ListOperations.scala:10)
        at com.redis.Redis$class.send(RedisClient.scala:22)
        at com.redis.RedisClient.send(RedisClient.scala:94)
        at com.redis.ListOperations$class.lpush(ListOperations.scala:10)
        at com.redis.RedisClient.lpush(RedisClient.scala:94)
```
```
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x000000008af22bf8> (a java.io.BufferedInputStream)
        at com.redis.IO$class.readCounted(IO.scala:117)
        at com.redis.RedisClient.readCounted(RedisClient.scala:94)
        at com.redis.Reply$$anonfun$4.applyOrElse(RedisProtocol.scala:68)
        at com.redis.Reply$$anonfun$4.applyOrElse(RedisProtocol.scala:63)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
        at com.redis.Reply$class.receive(RedisProtocol.scala:124)
        at com.redis.RedisClient.receive(RedisClient.scala:94)
        at com.redis.R$class.asBulk(RedisProtocol.scala:131)
        at com.redis.RedisClient.asBulk(RedisClient.scala:94)
        at com.redis.ListOperations$$anonfun$rpop$1.apply(ListOperations.scala:69)
        at com.redis.ListOperations$$anonfun$rpop$1.apply(ListOperations.scala:69)
        at com.redis.Redis$class.send(RedisClient.scala:22)
        at com.redis.RedisClient.send(RedisClient.scala:94)
        at com.redis.ListOperations$class.rpop(ListOperations.scala:69)
        at com.redis.RedisClient.rpop(RedisClient.scala:94)
```

Actually, the lpush seems to be locked by the rpop, and the rpop is waiting for something I don't know.
I don't understand why there is this lock, by the way, we're using client pooling and each of these action is in a separate .withClient{ } block and thread.

**Comment by mdespriee** [comment]
On the rpop side, this is may be related to this bug of the JDK https://bugs.openjdk.java.net/browse/JDK-8075484.
