### ISSUE TITLE
Protocol errors while talking to Redis in Amazon ElasticCache

### ISSUE THREAD

**Issue by satorg** [debasishg/scala-redis#301]
### Description

Intermittent issue.
Failing method: `RedisClient#set`
Example call:
```
redisClient.set("some/key/name", "1", NX, 10.minutes)
```
Example errors:
```
java.lang.Exception: Protocol error: Got ($,[B@33c1a89b) as initial reply byte
	at com.redis.Reply$$anonfun$errReply$1.applyOrElse(RedisProtocol.scala:133)
	at com.redis.Reply$$anonfun$errReply$1.applyOrElse(RedisProtocol.scala:131)
        ...
```
OR
```
java.lang.Exception: $-1
	at com.redis.Reply$$anonfun$errReply$1.applyOrElse(RedisProtocol.scala:132)
	at com.redis.Reply$$anonfun$errReply$1.applyOrElse(RedisProtocol.scala:131)
        ...
```

### Expected behavior

No exceptions should be raised for valid input values.

### Server version
```
> info server
# Server
redis_version:6.0.5
redis_mode:standalone
os:Amazon ElastiCache
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:0.0.0
```

### Library version

**net.debasishg:redisclient_2.13:3.42**

**Comment by Squrrli** [comment]
Any update to this?
